workflows:
  ios-workflow:
    name: iOS Build Unsigned (SPM)
    instance_type: mac_mini_m1
    scripts:
      - name: Build unsigned IPA
        script: |
          set -e # Bắt buộc: Dừng ngay lập tức nếu lệnh build thất bại

          # Build và ép file xuất ra thư mục build_dir hiện tại
          xcodebuild build -project App/App.xcodeproj -scheme App -destination 'generic/platform=iOS' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CONFIGURATION_BUILD_DIR=$PWD/build_dir
          
          # Đóng gói
          mkdir -p Payload
          cp -R build_dir/App.app Payload/
          zip -r App.ipa Payload
    artifacts:
      - App.ipa